### ISSUE TITLE
Create command don't work!

### ISSUE THREAD

**Issue by VitzyKindly** [rutkuli/Discord-Authbot#3]
Hi, the database is sucesfully conected, but !create command doesn't work, why? 
All tables are created, any fix?

**Comment by rutkuli** [comment]
Are you sure that you have correct collations and datatypes?

**Comment by VitzyKindly** [comment]
Yes, im sure! the other commands works but this no!

**Comment by rutkuli** [comment]
**Well run those Queries and try again**

**Comment by rutkuli** [comment]
[db.txt](https://github.com/rutkuli/Discord-Authbot/files/5893474/db.txt)

**Comment by VitzyKindly** [comment]
This Queries have errors.

**Comment by rutkuli** [comment]
Just tried that shit myself today after two years, and works just fine.

**Comment by VitzyKindly** [comment]
I have the same tables an the error is "An error occurred while performing
the operation."

**Comment by rutkuli** [comment]
Did you edit the MySQL connection information?

**Comment by VitzyKindly** [comment]
Sure! Simple question the command usage is for example "!create 01/01/2021
"?

**Comment by VitzyKindly** [comment]
The only logs that i see in console are
"-Rutkuli bot is online!
-Checking for expired keys...
-Checking for expired keys with ip address...
-Checking for expired keys...
-Checking for expired keys with ip address...
-Checking for expired keys...
-Checking for expired keys with ip address...
-Checking for expired keys...
-Checking for expired keys with ip address..."

**Comment by VitzyKindly** [comment]
??

**Comment by rutkuli** [comment]
Command usage is !create {time} {product}

**Comment by VitzyKindly** [comment]
Like "!create 01/01/2021 test

**Comment by VitzyKindly** [comment]
U can give me a valid example?

**Comment by VitzyKindly** [comment]
Ok i find it, "!create 1 second TEST" this will create a key for 1 seconds?
And why the bot doesn't give roles when u claim it?

**Comment by rutkuli** [comment]
!create 7d Test

**Comment by rutkuli** [comment]
And this project wasn't meant to give discord roles at all. This is about four years ols project which i have forgotten.

**Comment by rutkuli** [comment]
Also there is no error loggings in create command just add the error catches your self.
